---
# influxdb config
- include: influxdb.yml

# grafana config
- include: grafana_user.yml
- include: grafana_datasource.yml
- include: grafana_dashboard.yml

- name: add user
  user:
    name: "{{ ispstats_user }}"
    comment: "User for ISP Stats"
    createhome: no
    shell: /usr/sbin/nologin

- name: create install dir
  file:
    path: "{{ ispstats_path }}"
    state: directory
    owner: "{{ ispstats_user }}"
    group: "{{ ispstats_user }}"

- name: copy application
  template:
    src: ../stats.py
    dest: "{{ ispstats_path }}/stats.py"
    owner: "{{ ispstats_user }}"
    group: "{{ ispstats_user }}"
    mode: 0754

- name: checkout speedtest-cli
  git:
    repo: "{{ speedtest_repo }}"
    dest: "{{ speedtest_cli_path }}"

- name: change ownership of speedtest-cli
  file:
    dest: "{{ speedtest_cli_path }}"
    owner: "{{ ispstats_user }}"
    group: "{{ ispstats_user }}"
    recurse: yes
  changed_when: false

- name: Check if ispstats.timer exists
  stat: path=/etc/systemd/system/ispstats.timer
  register: ispstats_timer_status

- name: Stop ispstats.timer
  systemd: name=ispstats.timer state=stopped enabled=no
  when: ispstats_timer_status.stat.exists
  changed_when: false

- name: Check if ispstats.service exists
  stat: path=/etc/systemd/system/ispstats.service
  register: ispstats_service_status

- name: Stop ispstats.service
  systemd: name=ispstats.service state=stopped enabled=no
  when: ispstats_service_status.stat.exists
  changed_when: false

- name: install ispstats systemd unit file
  template:
    src: ispstats.service.j2
    dest: /etc/systemd/system/ispstats.service
    mode: 0664
    owner: root
    group: root
  notify: restart ispstats

- name: install ispstats systemd timer file
  template:
    src: ispstats.timer.j2
    dest: /etc/systemd/system/ispstats.timer
    mode: 0664
    owner: root
    group: root
  notify: restart ispstats
